Models/Transaccion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GASTOSMVC.Models
{
    public class Transaccion
    {
        public int IDGas { get; set; }
        public string WCBXGas { get; set; }
        public string WCBXGastos { get; set; }
        public string WDia1 { get; set; }
        public string WCBXMes1 { get; set; }
        public string WCBXYear1 { get; set; }
        public decimal dGastos { get; set; }
        public List<SelectListItem> LCBXGas { get; set; }
        public List<SelectListItem> LCBXDia1 { get; set; }
        public List<SelectListItem> LCBXMes1 { get; set; }
        public List<SelectListItem> LCBXYear1 { get; set; }
        public List<SelectListItem> LCBXGastos { get; set; }
    }
}

Controllers/TransaccionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GASTOSMVC.Models;

namespace GASTOSMVC.Controllers
{
    public class TransaccionController : Controller
    {
        // GET: Transaccion
        public ActionResult Index()
        {
            Transaccion oTrans = new Transaccion();
            string WDia1 = "00" + DateTime.Now.Day.ToString(); string nMes1 = "00" + DateTime.Now.Month.ToString();
            string XWDia1 = WDia1.Substring(WDia1.Length - 2, 2); string XWMes1 = nMes1.Substring(nMes1.Length - 2, 2); string nYear = DateTime.Now.Year.ToString();
            var oTras = LLenaCombos(oTrans);
            oTrans.WCBXGas = "0";
            oTrans.WDia1 = XWDia1; oTrans.WCBXMes1 = XWMes1; oTrans.WCBXYear1 = nYear; 
            return View(oTrans);
        }
        public ActionResult Act(int nIDGas)
        {
            Transaccion oTrans = new Transaccion();
            UtilTransaccion oUtilTrans = new UtilTransaccion();
            oTrans.IDGas = nIDGas;
            var oTras = LLenaCombos(oTrans);
            var rTrans = oUtilTrans.FNTransaccion(nIDGas.ToString());

            oTrans.WCBXGas = rTrans.WCBXGas;
            oTrans.WDia1 = rTrans.WDia1;
            oTrans.WCBXMes1 = rTrans.WCBXMes1; oTrans.WCBXYear1 = rTrans.WCBXYear1; oTrans.WCBXGastos = rTrans.WCBXGastos;
            oTrans.dGastos = rTrans.dGastos;

            return View("Index",oTrans);
        }
        [HttpPost]
        public ActionResult Guardar(FormCollection oForm) {
            string WIDGas = oForm["HDIDGas"].ToString();
            string WCBXGastos = oForm["WCBXGastos"].ToString();
            string WDia1 = oForm["WDia1"].ToString();
            string WCBXMes1 = oForm["WCBXMes1"].ToString();
            string WCBXYear1 = oForm["WCBXYear1"].ToString();
            string WGas = oForm["txtGas"].ToString();
            string WCBXGas = oForm["WCBXGas"].ToString();
            string WIDUsr = Request.Cookies["IDUsr"].Value;
            UtilTransaccion oGuardar = new UtilTransaccion();
            UtilFecha oFec = new UtilFecha();
            string WFecha = oFec.FNDevFecha(WDia1, WCBXMes1, WCBXYear1);
            oGuardar.SPGuardaTransaccion(WCBXGastos, WCBXGas, WFecha,WGas, WIDUsr, WIDGas);
            oGuardar = null;
            return RedirectToAction("Index", "Main");
        }

        private object LLenaCombos(Transaccion oTrans) {
            UtilTransGastos utilTransGastos = new UtilTransGastos();
            string WYear = utilTransGastos.oYear(); string WIDUsr = Request.Cookies["IDUsr"].Value;
            Combos oCBX = new Combos();
            oTrans.LCBXGas = oCBX.FNLLenaCB("0|1|-1", "Normal|Especial|Todos");
            oTrans.LCBXDia1 = oCBX.FNLLenaCB(utilTransGastos.aNDia, utilTransGastos.aDia); oTrans.LCBXMes1 = oCBX.FNLLenaCB(utilTransGastos.aNMes, utilTransGastos.aMes); oTrans.LCBXYear1 = oCBX.FNLLenaCB(WYear, WYear);
            oTrans.LCBXGastos = oCBX.FNLLenaCombo("Gastos", "IDGastos", "SP_CatGastos", "@IDUsr", WIDUsr);
            oCBX = null; utilTransGastos = null;
            return oTrans;
        }
    }
}

Views/Transaccion/Index.cshtml
@model GASTOSMVC.Models.Transaccion
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css" />
    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <link href="~/Tls/Tls.css" rel="stylesheet" />
    <script src="~/Tls/Tls.js"></script>
    <script type="text/javascript">        
        function fnEsActualiza() {
            if (!FNFrcWrt("cbxCatGastos", "Favor de seleccionar un concepto de Gasto", "cbxCatGastos")) return false;
            if (!FNFrcWrt("txtGas", "Favor de escribir una cantidad para tu gasto", "txtGas")) return false;
            if (!FNFrcWrtONLYBlanc("cbxGas", "Favor de seleccionar el tipo gasto", "cbxGas")) return false;
            if (!FNFrcWrt("cbxDia1", "Favor de seleccionar un Día", "cbxDia1")) return false;
            if (!FNFrcWrt("cbxMes1", "Favor de seleccionar un Mes", "cbxMes1")) return false;
            if (!FNFrcWrt("cbxYear1", "Favor de seleccionar un Mes", "cbxYear1")) return false;
            gEBI("Frm").action = "@Url.Action("Guardar", "Transaccion")"; gEBI("Frm").method = "post";
            gEBI("Frm").submit();
        }
    </script>
</head>
<body>
    <form id="Frm" name="Frm">
        <div class="container">
            <h2>Registro de Gastos</h2>
            <div class="form-group">
                <label for="sel1">Selecciona un Concepto:</label>
                @Html.DropDownListFor(m => m.WCBXGastos, Model.LCBXGastos, "-- Selecciona una opción --", new { @class = "form-control", @id = "cbxCatGastos" })
            </div>
            <div class="form-group">
                <label for="Fecha">Fecha:</label>
                @Html.DropDownListFor(m => m.WDia1, Model.LCBXDia1, "-- Selecciona un Día --", new { @class = "form-control", @id = "cbxDia1" })
                <br />
                @Html.DropDownListFor(m => m.WCBXMes1, Model.LCBXMes1, "-- Selecciona una Mes --", new { @class = "form-control", @id = "cbxMes1" })
                <br />
                @Html.DropDownListFor(m => m.WCBXYear1, Model.LCBXYear1, "-- Selecciona una opción --", new { @class = "form-control", @id = "cbxYear1" })
                <br />
            </div>
            <div class="form-group">
                <label for="GastoEsp">Gasto Especial</label>
                @Html.DropDownListFor(m => m.WCBXGas, Model.LCBXGas, "-- Selecciona un Gasto Especial --", new { @class = "form-control", @id = "cbxGas" })
            </div>

            <div class="form-group">
                <label for="Gasto">Gasto $</label>
                <input type="text" id="txtGas" name="txtGas" placeholder="Gasto" class="form-control" value="@Model.dGastos" onKeyDown="return FNOnlyNumDotFormat(this, event);" />
            </div>
            <input type="button" value="Guardar" CssClass="btn btn-default" OnClick="return fnEsActualiza();" />
        </div>
        <input type="hidden" id="HDIDGas" name="HDIDGas" value="@Model.IDGas" />
    </form>
</body>
</html>